spring:
  datasource:
    password: 1234QWER
    url: jdbc:postgresql://10.0.7.42:5432/education_project_vladi
    username: education_user
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: vladi
      password: v0000

    
        
